class CipherMap {
  static const Map<String, String> encryptMap = {
    "A": "V", "a": "v",
    "B": "O", "b": "o",
    "C": "L", "c": "l",
    "D": "K", "d": "k",
    "E": "S", "e": "s",
    "F": "W", "f": "w",
    "G": "A", "g": "a",
    "H": "G", "h": "g",
    "I": "E", "i": "e",
    "J": "N", "j": "n",
    "K": "B", "k": "b",
    "L": "C", "l": "c",
    "M": "D", "m": "d",
    "N": "F", "n": "f",
    "O": "H", "o": "h",
    "P": "I", "p": "i",
    "Q": "J", "q": "j",
    "R": "M", "r": "m",
    "S": "P", "s": "p",
    "T": "Q", "t": "q",
    "U": "R", "u": "r",
    "V": "T", "v": "t",
    "W": "U", "w": "u",
    "X": "Z", "x": "z",
    "Y": "X", "y": "x",
    "Z": "Y", "z": "y"
  };

  static const Map<String, String> decryptMap = {
    "V": "A", "v": "a",
    "O": "B", "o": "b",
    "L": "C", "l": "c",
    "K": "D", "k": "d",
    "S": "E", "s": "e",
    "W": "F", "w": "f",
    "A": "G", "a": "g",
    "G": "H", "g": "h",
    "E": "I", "e": "i",
    "N": "J", "n": "j",
    "B": "K", "b": "k",
    "C": "L", "c": "l",
    "D": "M", "d": "m",
    "F": "N", "f": "n",
    "H": "O", "h": "o",
    "I": "P", "i": "p",
    "J": "Q", "j": "q",
    "M": "R", "m": "r",
    "P": "S", "p": "s",
    "Q": "T", "q": "t",
    "R": "U", "r": "u",
    "T": "V", "t": "v",
    "U": "W", "u": "w",
    "Z": "X", "z": "x",
    "X": "Y", "x": "y",
    "Y": "Z", "y": "z"
  };
}